services:
  data-engine:
    build: .
    tty: true            
    stdin_open: true      
    volumes:
      - .:/workspace
    env_file:
      - .env              

  bi-dashboard:
    image: apache/superset
    ports:
      - "8088:8088"
    volumes:
      - ./quantum_data:/app/data
    env_file:
    - .env
    depends_on:
      - data-engine